apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux
  namespace: flux
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'image updated'
      signingKey:
        secretRef:
          name: flux-system
    push:
      branch: master
  update:
    path: ./nginx
    strategy: Setters
